version: '3'
services:
  luya_composer:
    image: composer:latest
    volumes:
      - ./:/app
    command: composer install
  luya_db:
    image: mysql:5.7
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: luya
      MYSQL_DATABASE: luya_core
      MYSQL_USER: luya
      MYSQL_PASSWORD: luya
  luya_web:
    image: luyadev/luya-docker:nginx-fpm-php74
    volumes:
      - ./:/app
